####################################################################################################
# +----------------------------------------------------------------------------------------------+ #
# |            _______    ________                                               __              | #
# |           |  ____|   |__   __|                                              | |              | #
# |           | |____      _| | ___  _   _ _ __ _ __   __ _ _ __ ___   ___ _ __ | |_             | #
# |           |  __\ \ /\ / / |/ _ \| | | | '__| '_ \ / _` | '_ ` _ \ / _ \ '_ \| __|            | #
# |           | |   \ V  V /| | (_) | |_| | |  | | | | (_| | | | | | |  __/ | | | |_             | #
# |           |_|    \_/\_/ |_|\___/ \__,_|_|  |_| |_|\__,_|_| |_| |_|\___|_| |_|\__|            | #
# |                                                                                              | #
# |                                   Made by: Kaotich00                                         | #
# |                                                                                              | #
# |                 SOURCE CODE: https://github.com/ForgottenWorld/FwTournament                  | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #
####################################################################################################

# +----------------------------------------------------------------------------------------------+ #
# |                                                                                              | #
# |                                  LOCALIZATION SETTINGS                                       | #
# |                                                                                              | #
# |                             Configure Localization settings                                  | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #

# Define the default launguage for the plugin. Available languages: english, italian
language: 'english'

# +----------------------------------------------------------------------------------------------+ #
# |                                                                                              | #
# |                                  CHALLONGE SETTINGS                                          | #
# |                                                                                              | #
# |                             Configure challonge API settings                                 | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #

# Specify your API configuration KEY
# If you are not sure where to find it, follow this guide:
# https://api.challonge.com/it/api.html
challonge_api_key: 'insert here your api key'

# This is the prefix that is added
# before the tournament name. Default: 'tournament'
# Tournament name: pvp_1_v_1
# Challonge tournament name: tournament_pvp_1_v_1
challonge_tournament_prefix: 'tournament'