name: Fwtournament
version: ${project.version}
main: me.kaotich00.fwtournament.Fwtournament
api-version: 1.13
authors: [Kaotich00]
description: PaperMC plugin for PvP Tournament
commands:
  torneo:
    description: Command for creating tournaments
    usage: /<command>
    aliases: [torneo, tournament]
  arena:
    description: Command for creating arenas
    usage: /<command>
    aliases: [arena]