name: Fwtournament
version: 0.0.1
main: me.kaotich00.fwtournament.Fwtournament
api-version: 1.13
authors: [Kaotich00]
description: PaperMC plugin for PvP Tournament
commands:
  torneo:
    description: Command for creating tournaments
    usage: /<command>
    aliases: [torneo, tournament]